---
title: "R Markdown training exercises"
author: "Ministry of Justice"
date: "14/03/2019"
output: 
  word_document: 
          reference_docx: mystyles.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
crimedata <- read.csv("crimedata.csv")
```


```{r echo=FALSE, include=FALSE}
library(dplyr)
crimedata <- arrange(crimedata,year)
maxcrimes <- max(crimedata$crimes)
```

## Exercises

Recreate the following plot and text using what you have learnt in this training. You may find the cheatsheet and help window useful. Check your code works by swapping between the two data sets as before. 

```{r echo=FALSE}

plot(crimedata,type="l",main="Total number of Crimes per year", xlab = "Year", ylab = "Crimes", ylim=c(0,maxcrimes)) 

#type="l" specifies line graph, main specifies title, x(y)lab specify x(y) axes titles, ylim specifies range of y axis i.e. 0 - max value

firstyear <- first(crimedata$year)
latestyear <- last(crimedata$year)
meancrimes <- round(mean(crimedata$crimes), digits = 1)
```


**For this crimes statistic we have data from `r firstyear` to `r latestyear`.**

*The mean number of crimes per year across this period was `r meancrimes`.* 



